jenkinsfile-v0.2
Changed the code due to this error
Passing y parameter for yes
ERROR: for webserver  no such image: sha256:968c3484dc058c43bfd199d8ada51bb72710ca878cc5d2401557e3483b3f1f46: No such image: sha256:968c3484dc058c43bfd199d8ada51bb72710ca878cc5d2401557e3483b3f1f46
The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]no such image: sha256:968c3484dc058c43bfd199d8ada51bb72710ca878cc5d2401557e3483b3f1f46: No such image: sha256:968c3484dc058c43bfd199d8ada51bb72710ca878cc5d2401557e3483b3f1f46